### ISSUE TITLE
Investigate ratings from 3rd party sites

### ISSUE THREAD

**Issue by marcin-mucha** [patrykzieba1993/foodtruck-radar#2]
Check if there are available APIs from Facebook, Tripadvisor, Forsquare and so on.

**Comment by patrykzieba1993** [comment]
1st stage: parse Facebook HTML.
2nd stage: use Facebook API.

There is a problem with App review (Facebook API access). We need to provide them a use cases (screenshots/screencasts). Will do it when details view in the mobile app is done.

Closing for now.
