### ISSUE TITLE
Endpoint for specific foodPoints

### ISSUE THREAD

**Issue by bananowaZyrafa** [patrykzieba1993/foodtruck-radar#5]
We gonna need an endpoint for specific foodPoints IDs given. It will help us handle the Favorites foodPoints managing.
It could be a POST method with specific IDs listed in the body of the request.

**Comment by patrykzieba1993** [comment]
👍 you can use `/restaurants` endpoint for that. See `ids` query param: http://foodtruck-radar.herokuapp.com/docs/#/Restaurants/get_restaurants

Example: `https://foodtruck-radar.herokuapp.com/restaurants?ids=[1,2,3]`
